build: # https://docs.spring.io/spring-boot/docs/current/reference/html/howto-properties-and-configuration.html
  version: '@project.version@'

### application settings ###
spring:
  mvc:
    ### Initialize Dispatcher servlet when application has started ###
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  aop:
    proxy-target-class: true
  main:
    banner-mode: 'off' #disable banner 
  jmx:
    enabled: false
    default-domain: portal-backend

  ### disable spring-boot's multipath resolver ###
  http:
    multipart:
      enabled: false

  ### Set the active profile here ###
  profiles:
    active: dev
